### ISSUE TITLE
Don't call IServiceProvider.GetService from MEF export constructors

### ISSUE THREAD

**Issue by madskristensen** [Microsoft/VSSDK-Analyzers#2] opened 2018-02-08 19:22 UTC
This could deadlock VS according to @AlexEyler

**Comment by AlexEyler** [comment] 2018-02-12 19:57
I wonder if this one should be extended to "Don't introduce thread dependencies to a MEF constructor". The diagnostic could be:
1. Any calls to a VS service that has threading dependencies (_very_ similar to VSTHRD010 - the fix would be pretty different, though, since we wouldn't want to switch to the main thread at any point in the constructor). This includes a GetService call as well.
1. Any thread switching in the constructor.

Code fixes would be pretty complex for this diagnostic, since it totally depends on what you're doing:
1. If you're calling GetService, you should probably move the GetService call to an AsyncLazy and then have the AsyncLazy factory create the service (which would happen on first use, which is hopefully _outside_ of the MEF ctor).
1. If you're calling into a service (e.g. IVsSolution.SetProperty()), then... I don't know. It really depends.
1. If you're thread switching in the constructor, the fix is to stop doing that :).

@AArnott thoughts?

**Comment by AArnott** [comment] 2018-02-12 21:26
Agree on all points. An analyzer without a code fix provider may be the way to go (at least initially) here.

**Comment by AArnott** [comment] 2018-02-17 21:58
Maybe we should do this after #10

**Comment by AlexEyler** [comment] 2018-02-18 18:11
Agreed, we'd probably want to re-use a lot of the code there.

**Comment by AArnott** [comment] 2018-02-19 05:33
Dupe of https://github.com/Microsoft/vs-threading/projects/1#card-1455219

**Comment by AArnott** [comment] 2018-02-20 04:16
Given I think it makes sense to keep general thread affinity checks inside the newly data-driven VSTHRD010 analyzer, I'm going to proceed with a MEF analyzer in vs-threading as well.

https://github.com/Microsoft/vs-threading/issues/214

**Closed by AArnott** 2018-02-20 04:16 UTC
Labels: Analyzer proposal
