### ISSUE TITLE
Produce warning when synchronous tool window is used

### ISSUE THREAD

**Issue by madskristensen** [Microsoft/VSSDK-Analyzers#30] opened 2018-02-27 19:50 UTC
AsyncToolWindow in 15.6 should be used if possible.

**Comment by AArnott** [comment] 2018-02-27 20:14
This is already done by VSSDK003 with 36760aa8

**Comment by AArnott** [comment] 2018-02-27 20:14
Dupe of #21

**Closed by AArnott** 2018-02-27 20:14 UTC
Labels: Analyzer proposal

**Comment by madskristensen** [comment] 2018-02-27 20:20
Awesome. Thanks
